Weekday.create!(weekday: "monday")
Weekday.create!(weekday: "tuesday")
Weekday.create!(weekday: "wednesday")
Weekday.create!(weekday: "thursday")
Weekday.create!(weekday: "friday")
Weekday.create!(weekday: "saturday")
Weekday.create!(weekday: "sunday")