Weekday.create!(weekday: "1")
Weekday.create!(weekday: "2")
Weekday.create!(weekday: "3")
Weekday.create!(weekday: "4")
Weekday.create!(weekday: "5")
Weekday.create!(weekday: "6")
Weekday.create!(weekday: "7")